a = input("Enter first number:")
b = input("Enter second number:")
print("The numbers are ", a,"and",b)
print("The addition of a and b is",(int(a)+int(b)))
print("The subtraction of a and b is",(int(a)-int(b)))
print("The multiplication of a and b is",(int(a)*int(b)))
print("The division of a and b is",(int(a)//int(b)))
print("The exponent of a and b is",(int(a)**int(b)))
